version: "3.8"
services:
  nginx:
    ports:
     - "80:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT} 
    command: node index.js  
  mongodb:
   environment:
    - MONGO_INITDB_ROOT_USERNAME=${DB_USER} 
    - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}    
    