version: "3.8"
services:
  nginx:
    image: nginx
    ports:
     - "8000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
     - ./.env  
    depends_on:
     - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:  
  