version: "3.8"
services:
  nginx:
    ports:
     - "80:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js  
  mongodb:
   environment:
    - MONGO_INITDB_ROOT_USERNAME=${DB_USER} 
    - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}    
    